### ISSUE TITLE
folder renaming breaks everything

### ISSUE THREAD

**Issue by samuelhackwill** [RandomLab/craft#2]
quand tu mutate par exemple une foret en champ, le robot sait plus où se trouvent les trucs qui étaient dans le folder

**Comment by jdpillon** [comment]
Il faut pour chaque élément de type Base utiliser la méthode check_path pour attribuer le nouveau chemin à l'élément en question

**Comment by jdpillon** [comment]
Dans mutate après la mutation :

for o in Robot.find(Base):
    o.check_path(self.id, o.filename)

Ça doit être un truc comme ça😉

**Comment by jdpillon** [comment]
Normalement c'est résolu !
