### ISSUE TITLE
La chasse aux cafards...

### ISSUE THREAD

**Issue by jdpillon** [RandomLab/craft#3]
Je pense qu'il manque une ligne dans la méthode update du robot :
global items

**Comment by samuelhackwill** [comment]
dac

**Comment by jdpillon** [comment]
le commit bc04d7a105ced983029d9a6f83dbe5d35d4d4541 doit régler le pb
(du moins j'espère ;-))
See U

**Comment by samuelhackwill** [comment]
ça marche, je teste tout de suite
merci jackda.

**Comment by samuelhackwill** [comment]
on dirait bien que ça fonctionne!
wp
